### PR TITLE
added Meeting Logs and Translations sections

### PR DESCRIPTION
**Pull request by thriftyMinnow**
Added 2 new sections.  Meeting Logs has the log of the 2/28/2019 Discord meeting.  The Translations section simply links to the main Readme file in the new Translations repo on github.  Attached is a picture of how these new sections look on the web page.

Screenshot from 2019-03-14 21-57-27

### CODE REVIEW

**Comment by BigslimVdub** [comment]
Man can we please change that AEOn.....

**Comment by thriftyMinnow** [comment]
ah .. yes, will change AEOn back to AEON.

**Review by BigslimVdub — APPROVED** [review]
Looks good!

**Review by BigslimVdub — APPROVED** [review]
Yup

**Pull request merged**
