### PR TITLE
An initial beta branch commit

### PR DESCRIPTION
**Pull request by sci-comp**
This commit trims TODO items and adds the Official Resources tab.

### CODE REVIEW

**Review by thriftyMinnow — CHANGES_REQUESTED** [review]
I like where you are going, to remove the unfinished broken links/sections etc.  But as I was thinking about this more, I would suggest we remedy this by simply commenting out the sections which are not finished, rather than deleting everything.

So in summary:
1) Don't delete those .md files in the _includes/ folder. (As long as they are not referenced anywhere, they will not appear on the site.)  For each one that we want to remove, put a comment at the top, saying something like "TODO:  finish this section for the web pages, and then uncomment the appropriate lines in the index.md file to display this section."
2) Modify index.md to simply comment out any accordion sections, using the HTML ` <!--    --> ` comment tags.  You can precede each comment block with something like `<!-- TODO: uncomment this block after the get-started.md page is complete in the _includes folder. -->`

This will allow all the original structure to still be stubbed in, in the repo, so we don't lose what we were thinking.  And the additional comments provide clear instructions for anyone down the road, on how to finish a section and display it.

**Comment by aeon1234** [comment]
I like @thriftyMinnow 's comment/review.
I cannot add a smiley to it, that's why I wrote a new comment to show it.

**Comment by camthegeek** [comment]
Commenting sections out via HTML comments would be the best thing to do.

**Comment by BigslimVdub** [comment]
I thought this was supposed to call the other repo pages we already set up in AeonCommunity such as "https://github.com/AEONCommunity/AeonHowTos/blob/master/MainIndex.md" or "https://github.com/AEONCommunity/Aeon-Community-Links/blob/master/Links.md".

So do we have to re-write these .md files now for this webpage?

**Comment by thriftyMinnow** [comment]
@BigslimVdub the github managed website theme does not work across repos.  We have to move each "repo" of content into a sub-folder of the github-pages repo.  then we can link to it.

So, instead of mutliple content-related repos, we would have multiple content-related folders inside this repo.  And we would only keep separate repos for aeon projects that are more than content for the website ... like the funding system repo, etc.

**Pull request closed without merging**
